os: linux
language: node_js
node_js:
  - 'lts/*'
cache:
  - npm

install:
  - npm ci

jobs:
  include:
    - name: 'Package audit'
      script: npm audit
    - name: 'Lint'
      script: npm run lint
    - name: 'Test'
      script: npm test
    - name: 'Build'
      script: npm run build
